//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicBuilder.Workflow.Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicBuilder.Workflow.Activities.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one constructor for type &quot;{0}&quot; that would match the specified parameters. .
        /// </summary>
        internal static string AmbiguousConstructor {
            get {
                return ResourceManager.GetString("AmbiguousConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous user defined conversions for converting &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string AmbiguousConversion {
            get {
                return ResourceManager.GetString("AmbiguousConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one indexer was found that would match the specified arguments..
        /// </summary>
        internal static string AmbiguousIndexerMatch {
            get {
                return ResourceManager.GetString("AmbiguousIndexerMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one method was found with the name &quot;{0}&quot; that would match the specified parameters. .
        /// </summary>
        internal static string AmbiguousMatch {
            get {
                return ResourceManager.GetString("AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator &apos;{0}&apos; is ambiguous between the following methods: &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string AmbiguousOperator {
            get {
                return ResourceManager.GetString("AmbiguousOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic operator &quot;{0}&quot; cannot be used on operands of types &quot;{1}&quot; and &quot;{2}&quot;..
        /// </summary>
        internal static string ArithOpBadTypes {
            get {
                return ResourceManager.GetString("ArithOpBadTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of indices; expected {0}..
        /// </summary>
        internal static string ArrayIndexBadRank {
            get {
                return ResourceManager.GetString("ArrayIndexBadRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; cannot be used as an array index..
        /// </summary>
        internal static string ArrayIndexBadType {
            get {
                return ResourceManager.GetString("ArrayIndexBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of an array cannot be specified twice..
        /// </summary>
        internal static string ArraySizeBoth {
            get {
                return ResourceManager.GetString("ArraySizeBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of an array cannot be less than 0..
        /// </summary>
        internal static string ArraySizeInvalid {
            get {
                return ResourceManager.GetString("ArraySizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the array size (&quot;{0}&quot;) is invalid..
        /// </summary>
        internal static string ArraySizeTypeInvalid {
            get {
                return ResourceManager.GetString("ArraySizeTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single dimensional arrays are allowed. Defining an array of type &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string ArrayTypeInvalid {
            get {
                return ResourceManager.GetString("ArrayTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment could not be executed as the field or property to be assigned to is null..
        /// </summary>
        internal static string AssignLeftNull {
            get {
                return ResourceManager.GetString("AssignLeftNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression type &quot;{0}&quot; is not assignable to the field/property of type &quot;{1}&quot;..
        /// </summary>
        internal static string AssignNotAllowed {
            get {
                return ResourceManager.GetString("AssignNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment could not be executed as the left side must represent a field or property..
        /// </summary>
        internal static string AssignNotHandled {
            get {
                return ResourceManager.GetString("AssignNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment could not be executed as the expression to be assigned is null..
        /// </summary>
        internal static string AssignRightNull {
            get {
                return ResourceManager.GetString("AssignRightNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}.{1}&quot;.
        /// </summary>
        internal static string AttributeFieldName {
            get {
                return ResourceManager.GetString("AttributeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &quot;{0}.{1}&quot; .
        /// </summary>
        internal static string AttributeMethodName {
            get {
                return ResourceManager.GetString("AttributeMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a &quot;{1}&quot; that specifies &quot;{2}&quot;, but no matching method or property was found.
        /// </summary>
        internal static string AttributeMethodNotFound {
            get {
                return ResourceManager.GetString("AttributeMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}.{1}&quot;.
        /// </summary>
        internal static string AttributePropertyName {
            get {
                return ResourceManager.GetString("AttributePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a &quot;{1}&quot; that specifies  &quot;{2}&quot;, but no matching property or field is found.
        /// </summary>
        internal static string AttributePropertyNotFound {
            get {
                return ResourceManager.GetString("AttributePropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to evaluate operator {0} on types &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string BinaryOpFails {
            get {
                return ResourceManager.GetString("BinaryOpFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string BinaryOpNotSupported {
            get {
                return ResourceManager.GetString("BinaryOpNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &quot;{0}&quot; on type &quot;{1}&quot; cannot be accessed because it is internal..
        /// </summary>
        internal static string CannotAccessInternalMember {
            get {
                return ResourceManager.GetString("CannotAccessInternalMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &quot;{0}&quot; on type &quot;{1}&quot; cannot be accessed because it is private..
        /// </summary>
        internal static string CannotAccessPrivateMember {
            get {
                return ResourceManager.GetString("CannotAccessPrivateMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null object cannot be converted to value type &quot;{0}&quot;..
        /// </summary>
        internal static string CannotCastNullToValueType {
            get {
                return ResourceManager.GetString("CannotCastNullToValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing not supported on type &quot;{0}&quot;..
        /// </summary>
        internal static string CannotIndexType {
            get {
                return ResourceManager.GetString("CannotIndexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to an expression of this type..
        /// </summary>
        internal static string CannotWriteToExpression {
            get {
                return ResourceManager.GetString("CannotWriteToExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast from type &quot;{0}&quot; to type &quot;{1}&quot;..
        /// </summary>
        internal static string CastIncompatibleTypes {
            get {
                return ResourceManager.GetString("CastIncompatibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null value to type &quot;{0}&quot;..
        /// </summary>
        internal static string CastOfNullInvalid {
            get {
                return ResourceManager.GetString("CastOfNullInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions of type &quot;{0}&quot; are not supported..
        /// </summary>
        internal static string CodeExpressionNotHandled {
            get {
                return ResourceManager.GetString("CodeExpressionNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements of type &quot;{0}&quot; are not supported..
        /// </summary>
        internal static string CodeStatementNotHandled {
            get {
                return ResourceManager.GetString("CodeStatementNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected condition?.
        /// </summary>
        internal static string ConditionConfirmDeleteMessageText {
            get {
                return ResourceManager.GetString("ConditionConfirmDeleteMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a rule condition to be assigned to the activity&apos;s condition. You can also add, edit, delete or rename existing conditions..
        /// </summary>
        internal static string ConditionDescriptionText {
            get {
                return ResourceManager.GetString("ConditionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition name must be unique. Please type a unique name for the condition, or click Cancel..
        /// </summary>
        internal static string ConditionDuplicateNameErrorText {
            get {
                return ResourceManager.GetString("ConditionDuplicateNameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Editor.
        /// </summary>
        internal static string ConditionEditor {
            get {
                return ResourceManager.GetString("ConditionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition must have a name. Please type a name for the condition, or click Cancel..
        /// </summary>
        internal static string ConditionEmptyNameErrorText {
            get {
                return ResourceManager.GetString("ConditionEmptyNameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition &quot;{0}&quot; already exists. Specify a unique name for this new condition..
        /// </summary>
        internal static string ConditionExists {
            get {
                return ResourceManager.GetString("ConditionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Expression.
        /// </summary>
        internal static string ConditionExpression {
            get {
                return ResourceManager.GetString("ConditionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition expression can not be null..
        /// </summary>
        internal static string ConditionExpressionNull {
            get {
                return ResourceManager.GetString("ConditionExpressionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition expression must evaluate to true or false..
        /// </summary>
        internal static string ConditionMustBeBoolean {
            get {
                return ResourceManager.GetString("ConditionMustBeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition &quot;{0}&quot; being updated does not match the name of the original (&quot;{1}&quot;)..
        /// </summary>
        internal static string ConditionNameNotIdentical {
            get {
                return ResourceManager.GetString("ConditionNameNotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition name is not set.  Specify a name for this condition before editing the expression..
        /// </summary>
        internal static string ConditionNameNotSet {
            get {
                return ResourceManager.GetString("ConditionNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name for condition:.
        /// </summary>
        internal static string ConditionNewNameLableText {
            get {
                return ResourceManager.GetString("ConditionNewNameLableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the condition &quot;{0}&quot;..
        /// </summary>
        internal static string ConditionNotFound {
            get {
                return ResourceManager.GetString("ConditionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Preview.
        /// </summary>
        internal static string ConditionPreviewLabelText {
            get {
                return ResourceManager.GetString("ConditionPreviewLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Condition.
        /// </summary>
        internal static string ConditionRenameTitleText {
            get {
                return ResourceManager.GetString("ConditionRenameTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Condition.
        /// </summary>
        internal static string ConditionTitleText {
            get {
                return ResourceManager.GetString("ConditionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to evaluate Condition &quot;{0}&quot; as there are validation errors..
        /// </summary>
        internal static string ConditionValidationFailed {
            get {
                return ResourceManager.GetString("ConditionValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No constructor matched the supplied arguments..
        /// </summary>
        internal static string ConstructorOverloadNotFound {
            get {
                return ResourceManager.GetString("ConstructorOverloadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generator context stack does not contain required item of type &quot;{0}&quot;..
        /// </summary>
        internal static string ContextStackItemMissing {
            get {
                return ResourceManager.GetString("ContextStackItemMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generator context stack is missing from current ValidationManager..
        /// </summary>
        internal static string ContextStackMissing {
            get {
                return ResourceManager.GetString("ContextStackMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the member &quot;{0}&quot; could not be determined.  Ensure that the declaration is correct..
        /// </summary>
        internal static string CouldNotDetermineMemberType {
            get {
                return ResourceManager.GetString("CouldNotDetermineMemberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cycle was detected in the expression..
        /// </summary>
        internal static string CyclicalExpression {
            get {
                return ResourceManager.GetString("CyclicalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit the workflow in debug mode..
        /// </summary>
        internal static string DebugModeEditsDisallowed {
            get {
                return ResourceManager.GetString("DebugModeEditsDisallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Condition.
        /// </summary>
        internal static string DeleteCondition {
            get {
                return ResourceManager.GetString("DeleteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rule.
        /// </summary>
        internal static string DeleteRule {
            get {
                return ResourceManager.GetString("DeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Rule Set.
        /// </summary>
        internal static string DeleteRuleSet {
            get {
                return ResourceManager.GetString("DeleteRuleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one condition named &quot;{0}&quot; was found in the condition collection. Only the first condition will be used. Make sure all conditions have unique names..
        /// </summary>
        internal static string DuplicateConditions {
            get {
                return ResourceManager.GetString("DuplicateConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELSE.
        /// </summary>
        internal static string Else {
            get {
                return ResourceManager.GetString("Else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the Action(s):.
        /// </summary>
        internal static string Error_ActionsParser {
            get {
                return ResourceManager.GetString("Error_ActionsParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error building the condition:.
        /// </summary>
        internal static string Error_ConditionParser {
            get {
                return ResourceManager.GetString("Error_ConditionParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configuration file is either missing or does not contain authorizedTypes related configuration information..
        /// </summary>
        internal static string Error_ConfigFileMissingOrInvalid {
            get {
                return ResourceManager.GetString("Error_ConfigFileMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered while executing the constructor on {0}: {1}.
        /// </summary>
        internal static string Error_ConstructorInvoke {
            get {
                return ResourceManager.GetString("Error_ConstructorInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rule. Another rule of that name exists in the rule set..
        /// </summary>
        internal static string Error_DuplicateRuleName {
            get {
                return ResourceManager.GetString("Error_DuplicateRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some part of the expression is not supported . Action canceled..
        /// </summary>
        internal static string Error_ExpressionNotSupported {
            get {
                return ResourceManager.GetString("Error_ExpressionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is invalid. Please type an integer value..
        /// </summary>
        internal static string Error_InvalidPriority {
            get {
                return ResourceManager.GetString("Error_InvalidPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered while executing method {0}.{1}: {2}.
        /// </summary>
        internal static string Error_MethodInvoke {
            get {
                return ResourceManager.GetString("Error_MethodInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered while getting the property {0}.{1}: {2}.
        /// </summary>
        internal static string Error_PropertyGet {
            get {
                return ResourceManager.GetString("Error_PropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered while setting the property {0}.{1}: {2}.
        /// </summary>
        internal static string Error_PropertySet {
            get {
                return ResourceManager.GetString("Error_PropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is invalid. Rule name cannot be empty..
        /// </summary>
        internal static string Error_RuleNameIsEmpty {
            get {
                return ResourceManager.GetString("Error_RuleNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not marked as authorized in the application configuration file..
        /// </summary>
        internal static string Error_TypeNotAuthorized {
            get {
                return ResourceManager.GetString("Error_TypeNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not report errors when validating sub-expression. Errors property is null for RuleValidation instance associated with type &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorsCollectionMissing {
            get {
                return ResourceManager.GetString("ErrorsCollectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit Update Only.
        /// </summary>
        internal static string ExplicitUpdateOnly {
            get {
                return ResourceManager.GetString("ExplicitUpdateOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression was not validated..
        /// </summary>
        internal static string ExpressionNotValidated {
            get {
                return ResourceManager.GetString("ExpressionNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the expression to be associated with the the Rule Expression condition&apos;s name..
        /// </summary>
        internal static string ExpressionPropertyDescription {
            get {
                return ResourceManager.GetString("ExpressionPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{0}&quot; on type &quot;{1}&quot; is a literal and can not be set..
        /// </summary>
        internal static string FieldSetNotAllowed {
            get {
                return ResourceManager.GetString("FieldSetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Chaining.
        /// </summary>
        internal static string FullChaining {
            get {
                return ResourceManager.GetString("FullChaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic methods are not supported..
        /// </summary>
        internal static string GenericMethodsNotSupported {
            get {
                return ResourceManager.GetString("GenericMethodsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic operator &quot;{1}&quot; is not valid on operands of types &quot;{0}&quot; and &quot;{2}&quot;..
        /// </summary>
        internal static string IncompatibleArithmeticTypes {
            get {
                return ResourceManager.GetString("IncompatibleArithmeticTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operands of types &quot;{0}&quot; and &quot;{1}&quot; can not be compared..
        /// </summary>
        internal static string IncompatibleComparisonTypes {
            get {
                return ResourceManager.GetString("IncompatibleComparisonTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operands of type &quot;{0}&quot; can not be compared with null..
        /// </summary>
        internal static string IncompatibleNullTypes {
            get {
                return ResourceManager.GetString("IncompatibleNullTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices may not be &quot;ref&quot; or &quot;out&quot;..
        /// </summary>
        internal static string IndexerArgCannotBeRefOrOut {
            get {
                return ResourceManager.GetString("IndexerArgCannotBeRefOrOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No indexer property was found that takes {0} arguments..
        /// </summary>
        internal static string IndexerCountMismatch {
            get {
                return ResourceManager.GetString("IndexerCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No indexer properties were found on type &quot;{0}&quot;..
        /// </summary>
        internal static string IndexerNotFound {
            get {
                return ResourceManager.GetString("IndexerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overloaded indexer property matched the supplied arguments..
        /// </summary>
        internal static string IndexerOverloadNotFound {
            get {
                return ResourceManager.GetString("IndexerOverloadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexer operations cannot be static..
        /// </summary>
        internal static string IndexersCannotBeStatic {
            get {
                return ResourceManager.GetString("IndexersCannotBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of initializers specified ({0}) is greater than the array dimension specified ({1})..
        /// </summary>
        internal static string InitializerCountMismatch {
            get {
                return ResourceManager.GetString("InitializerCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializer {0} of the constructor for type {1}[] does not match the expected type..
        /// </summary>
        internal static string InitializerMismatch {
            get {
                return ResourceManager.GetString("InitializerMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert type &apos;{0}&apos; to type &apos;{1}&apos; as determined when the expression was validated..
        /// </summary>
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; has invalid value. Condition expression is invalid..
        /// </summary>
        internal static string InvalidConditionExpression {
            get {
                return ResourceManager.GetString("InvalidConditionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; has invalid value. Condition name is invalid..
        /// </summary>
        internal static string InvalidConditionName {
            get {
                return ResourceManager.GetString("InvalidConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Condition Name.
        /// </summary>
        internal static string InvalidConditionNameCaption {
            get {
                return ResourceManager.GetString("InvalidConditionNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters passed as &quot;ref&quot; or &quot;out&quot; parameters must be fields..
        /// </summary>
        internal static string InvalidOutRefParameter {
            get {
                return ResourceManager.GetString("InvalidOutRefParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; was not found in member &quot;{1}&quot;..
        /// </summary>
        internal static string InvalidRuleAttributeParameter {
            get {
                return ResourceManager.GetString("InvalidRuleAttributeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; has an invalid value. Rule set is invalid..
        /// </summary>
        internal static string InvalidRuleSetExpression {
            get {
                return ResourceManager.GetString("InvalidRuleSetExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; has an invalid value. Rule set name is invalid..
        /// </summary>
        internal static string InvalidRuleSetName {
            get {
                return ResourceManager.GetString("InvalidRuleSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wildcard &apos;*&apos; is only allowed as the last part of the path in an Update action or RuleAttribute..
        /// </summary>
        internal static string InvalidWildCardInPathQualifier {
            get {
                return ResourceManager.GetString("InvalidWildCardInPathQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleInvokeAttribute may not refer to method or property &quot;{0}&quot; which specifies a read or write of a parameter..
        /// </summary>
        internal static string InvokeAttrRefersToParameterAttribute {
            get {
                return ResourceManager.GetString("InvokeAttrRefersToParameterAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement could not be executed as the expression must be a method invocation..
        /// </summary>
        internal static string InvokeNotHandled {
            get {
                return ResourceManager.GetString("InvokeNotHandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement could not be executed as the method invoke expression is null..
        /// </summary>
        internal static string InvokeStatementNull {
            get {
                return ResourceManager.GetString("InvokeStatementNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression to the left of the logical operator &quot;{0}&quot; must return a Boolean result. Currently it evaluates to type &quot;{1}&quot;..
        /// </summary>
        internal static string LogicalOpBadTypeLHS {
            get {
                return ResourceManager.GetString("LogicalOpBadTypeLHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression to the right of the logical operator &quot;{0}&quot; must return a Boolean result. Currently it evaluates to type &quot;{1}&quot;..
        /// </summary>
        internal static string LogicalOpBadTypeRHS {
            get {
                return ResourceManager.GetString("LogicalOpBadTypeRHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No method named &quot;{0}&quot; was found that takes {1} arguments..
        /// </summary>
        internal static string MethodArgCountMismatch {
            get {
                return ResourceManager.GetString("MethodArgCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} to method &quot;{1}&quot; cannot be converted from &quot;{2}&quot; to &quot;{3}&quot;..
        /// </summary>
        internal static string MethodArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("MethodArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} to method &quot;{1}&quot; must be passed with the &quot;{2}&quot; specifier..
        /// </summary>
        internal static string MethodDirectionMismatch {
            get {
                return ResourceManager.GetString("MethodDirectionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No overloaded method &quot;{0}&quot; matched the supplied arguments..
        /// </summary>
        internal static string MethodOverloadNotFound {
            get {
                return ResourceManager.GetString("MethodOverloadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No index expressions were specified..
        /// </summary>
        internal static string MissingIndexExpressions {
            get {
                return ResourceManager.GetString("MissingIndexExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initializers for the array of type &quot;{0}&quot; can not be null..
        /// </summary>
        internal static string MissingInitializer {
            get {
                return ResourceManager.GetString("MissingInitializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rule must specify a valid condition..
        /// </summary>
        internal static string MissingRuleCondition {
            get {
                return ResourceManager.GetString("MissingRuleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service &quot;{0}&quot; must be installed for this operation to succeed.  Ensure that this service is available..
        /// </summary>
        internal static string MissingService {
            get {
                return ResourceManager.GetString("MissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the name of the Rule Expression condition..
        /// </summary>
        internal static string NamePropertyDescription {
            get {
                return ResourceManager.GetString("NamePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string NewConditionName {
            get {
                return ResourceManager.GetString("NewConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string NewRuleName {
            get {
                return ResourceManager.GetString("NewRuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Set.
        /// </summary>
        internal static string NewRuleSetName {
            get {
                return ResourceManager.GetString("NewRuleSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object used is not an Activity..
        /// </summary>
        internal static string NoActivity {
            get {
                return ResourceManager.GetString("NoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not convert from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string NoConversion {
            get {
                return ResourceManager.GetString("NoConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help topic is not implemented..
        /// </summary>
        internal static string NoHelp {
            get {
                return ResourceManager.GetString("NoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object reference is required for non-static member &quot;{0}&quot;..
        /// </summary>
        internal static string NonStaticMember {
            get {
                return ResourceManager.GetString("NonStaticMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a RuleConditionReference..
        /// </summary>
        internal static string NotARuleConditionReference {
            get {
                return ResourceManager.GetString("NotARuleConditionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects of type &quot;{0}&quot; do not support ICloneable, and can not be cloned..
        /// </summary>
        internal static string NotCloneable {
            get {
                return ResourceManager.GetString("NotCloneable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The left side of an assignment statement must represent a field or property..
        /// </summary>
        internal static string NullAssignLeft {
            get {
                return ResourceManager.GetString("NullAssignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The right side of an assignment statement must represent an expression to be evaluated..
        /// </summary>
        internal static string NullAssignRight {
            get {
                return ResourceManager.GetString("NullAssignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression to the left of operator &quot;{0}&quot; can not be null..
        /// </summary>
        internal static string NullBinaryOpLHS {
            get {
                return ResourceManager.GetString("NullBinaryOpLHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression to the right of operator &quot;{0}&quot; can not be null..
        /// </summary>
        internal static string NullBinaryOpRHS {
            get {
                return ResourceManager.GetString("NullBinaryOpRHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operand of the cast operator cannot be null..
        /// </summary>
        internal static string NullCastExpr {
            get {
                return ResourceManager.GetString("NullCastExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target type of the cast operator is missing..
        /// </summary>
        internal static string NullCastType {
            get {
                return ResourceManager.GetString("NullCastType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} to constructor of type &quot;{1}&quot; can not be null..
        /// </summary>
        internal static string NullConstructorParameter {
            get {
                return ResourceManager.GetString("NullConstructorParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type parameter specified for parameter {0} of the constructor for type {1} can not be null..
        /// </summary>
        internal static string NullConstructorTypeParameter {
            get {
                return ResourceManager.GetString("NullConstructorTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target expression for the direction specifier cannot be null..
        /// </summary>
        internal static string NullDirectionTarget {
            get {
                return ResourceManager.GetString("NullDirectionTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object for field &quot;{0}&quot; can not be null..
        /// </summary>
        internal static string NullFieldTarget {
            get {
                return ResourceManager.GetString("NullFieldTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target object for the indexer operation cannot be null..
        /// </summary>
        internal static string NullIndexerTarget {
            get {
                return ResourceManager.GetString("NullIndexerTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index expression cannot be null..
        /// </summary>
        internal static string NullIndexExpression {
            get {
                return ResourceManager.GetString("NullIndexExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expression must be specified for the expression statement..
        /// </summary>
        internal static string NullInvokeStatementExpression {
            get {
                return ResourceManager.GetString("NullInvokeStatementExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} to method &quot;{1}&quot; can not be null..
        /// </summary>
        internal static string NullMethodParameter {
            get {
                return ResourceManager.GetString("NullMethodParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object for method &quot;{0}&quot; can not be null..
        /// </summary>
        internal static string NullMethodTarget {
            get {
                return ResourceManager.GetString("NullMethodTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type parameter specified for parameter {0} of method &quot;{1}&quot; can not be null..
        /// </summary>
        internal static string NullMethodTypeParameter {
            get {
                return ResourceManager.GetString("NullMethodTypeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object for property &quot;{0}&quot; can not be null..
        /// </summary>
        internal static string NullPropertyTarget {
            get {
                return ResourceManager.GetString("NullPropertyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statement cannot be null..
        /// </summary>
        internal static string NullStatement {
            get {
                return ResourceManager.GetString("NullStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type specified for an Expression can not be null..
        /// </summary>
        internal static string NullTypeType {
            get {
                return ResourceManager.GetString("NullTypeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field or property for an Update action cannot be null.
        /// </summary>
        internal static string NullUpdate {
            get {
                return ResourceManager.GetString("NullUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;null value&gt;.
        /// </summary>
        internal static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of type arguments for generic type &quot;{0}&quot;..
        /// </summary>
        internal static string Parser_BadTypeArgCount {
            get {
                return ResourceManager.GetString("Parser_BadTypeArgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition can not be empty..
        /// </summary>
        internal static string Parser_EmptyExpression {
            get {
                return ResourceManager.GetString("Parser_EmptyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra characters ignored..
        /// </summary>
        internal static string Parser_ExtraCharactersIgnored {
            get {
                return ResourceManager.GetString("Parser_ExtraCharactersIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string Parser_InvalidCharacter {
            get {
                return ResourceManager.GetString("Parser_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid decimal constant.  {0}.
        /// </summary>
        internal static string Parser_InvalidDecimalConstant {
            get {
                return ResourceManager.GetString("Parser_InvalidDecimalConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The escape sequence &apos;\{0}&apos; is not valid..
        /// </summary>
        internal static string Parser_InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("Parser_InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &apos;{0}&apos; in floating point exponent..
        /// </summary>
        internal static string Parser_InvalidExponentDigit {
            get {
                return ResourceManager.GetString("Parser_InvalidExponentDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid floating point constant.  {0}.
        /// </summary>
        internal static string Parser_InvalidFloatingPointConstant {
            get {
                return ResourceManager.GetString("Parser_InvalidFloatingPointConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &apos;{0}&apos; in hexadecimal number..
        /// </summary>
        internal static string Parser_InvalidHexDigit {
            get {
                return ResourceManager.GetString("Parser_InvalidHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer constant.  {0}.
        /// </summary>
        internal static string Parser_InvalidIntegerConstant {
            get {
                return ResourceManager.GetString("Parser_InvalidIntegerConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new expression requires () or [] after type..
        /// </summary>
        internal static string Parser_InvalidNew {
            get {
                return ResourceManager.GetString("Parser_InvalidNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type argument..
        /// </summary>
        internal static string Parser_InvalidTypeArgument {
            get {
                return ResourceManager.GetString("Parser_InvalidTypeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update path must be a string literal, or an expression that produces a single side effect path..
        /// </summary>
        internal static string Parser_InvalidUpdateExpression {
            get {
                return ResourceManager.GetString("Parser_InvalidUpdateExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;&gt;&apos; at end of generic type argument list..
        /// </summary>
        internal static string Parser_MissingCloseAngleBracket {
            get {
                return ResourceManager.GetString("Parser_MissingCloseAngleBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;]&apos; at end of array index..
        /// </summary>
        internal static string Parser_MissingCloseSquareBracket {
            get {
                return ResourceManager.GetString("Parser_MissingCloseSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;]&apos; at end of array specification..
        /// </summary>
        internal static string Parser_MissingCloseSquareBracket1 {
            get {
                return ResourceManager.GetString("Parser_MissingCloseSquareBracket1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &quot;.&quot; is expected after a namespace..
        /// </summary>
        internal static string Parser_MissingDotAfterNamespace {
            get {
                return ResourceManager.GetString("Parser_MissingDotAfterNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identifier was expected after the dot (.) operator..
        /// </summary>
        internal static string Parser_MissingIdentifierAfterDot {
            get {
                return ResourceManager.GetString("Parser_MissingIdentifierAfterDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;(&apos; is expected after the &quot;{0}&quot; statement..
        /// </summary>
        internal static string Parser_MissingLparenAfterCommand {
            get {
                return ResourceManager.GetString("Parser_MissingLparenAfterCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing operand..
        /// </summary>
        internal static string Parser_MissingOperand {
            get {
                return ResourceManager.GetString("Parser_MissingOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;}&apos; at the end of an initializer list was not found..
        /// </summary>
        internal static string Parser_MissingRCurlyAfterInitializers {
            get {
                return ResourceManager.GetString("Parser_MissingRCurlyAfterInitializers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;)&apos; at the end of an argument list was not found..
        /// </summary>
        internal static string Parser_MissingRParenAfterArgumentList {
            get {
                return ResourceManager.GetString("Parser_MissingRParenAfterArgumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;)&apos; and the end of a parenthesized sub expression was not found..
        /// </summary>
        internal static string Parser_MissingRParenInSubexpression {
            get {
                return ResourceManager.GetString("Parser_MissingRParenInSubexpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type arguments are required for generic type &quot;{0}&quot;..
        /// </summary>
        internal static string Parser_MissingTypeArguments {
            get {
                return ResourceManager.GetString("Parser_MissingTypeArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No array size or initializers were specified..
        /// </summary>
        internal static string Parser_NoArrayCreationSize {
            get {
                return ResourceManager.GetString("Parser_NoArrayCreationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type arguments are not allowed with non-generic type &quot;{0}&quot;..
        /// </summary>
        internal static string Parser_NotAGenericType {
            get {
                return ResourceManager.GetString("Parser_NotAGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier &quot;{0}&quot; could not be resolved..
        /// </summary>
        internal static string Parser_UnknownIdentifier {
            get {
                return ResourceManager.GetString("Parser_UnknownIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized literal expression..
        /// </summary>
        internal static string Parser_UnknownLiteral {
            get {
                return ResourceManager.GetString("Parser_UnknownLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier &quot;{0}&quot; could not be found within namespace &quot;{1}&quot;..
        /// </summary>
        internal static string Parser_UnknownNamespaceMember {
            get {
                return ResourceManager.GetString("Parser_UnknownNamespaceMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated character literal..
        /// </summary>
        internal static string Parser_UnterminatedCharacterLiteral {
            get {
                return ResourceManager.GetString("Parser_UnterminatedCharacterLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string literal..
        /// </summary>
        internal static string Parser_UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("Parser_UnterminatedStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string ReevaluationAlways {
            get {
                return ResourceManager.GetString("ReevaluationAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string ReevaluationNever {
            get {
                return ResourceManager.GetString("ReevaluationNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relational operator &quot;{0}&quot; cannot be used on operands of types &quot;{1}&quot; and &quot;{2}&quot;..
        /// </summary>
        internal static string RelationalOpBadTypes {
            get {
                return ResourceManager.GetString("RelationalOpBadTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected rule?.
        /// </summary>
        internal static string RuleConfirmDeleteMessageText {
            get {
                return ResourceManager.GetString("RuleConfirmDeleteMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule name may not be empty or null..
        /// </summary>
        internal static string RuleNameMissing {
            get {
                return ResourceManager.GetString("RuleNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Set.
        /// </summary>
        internal static string RuleSet {
            get {
                return ResourceManager.GetString("RuleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected rule set?.
        /// </summary>
        internal static string RuleSetConfirmDeleteMessageText {
            get {
                return ResourceManager.GetString("RuleSetConfirmDeleteMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a rule set to be assigned to the PolicyActivity. You can also add, edit, delete or rename an existing rule set..
        /// </summary>
        internal static string RuleSetDescriptionText {
            get {
                return ResourceManager.GetString("RuleSetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule set name must be unique. Please type a unique name for the rule set, or click Cancel..
        /// </summary>
        internal static string RuleSetDuplicateNameErrorText {
            get {
                return ResourceManager.GetString("RuleSetDuplicateNameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule set must have a name. Please type a name for the rule set, or click Cancel..
        /// </summary>
        internal static string RuleSetEmptyNameErrorText {
            get {
                return ResourceManager.GetString("RuleSetEmptyNameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule set &quot;{0}&quot; already exists. Specify a unique name for this new rule set..
        /// </summary>
        internal static string RuleSetExists {
            get {
                return ResourceManager.GetString("RuleSetExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule set name is not set.  Specify a name for this rule set before editing it..
        /// </summary>
        internal static string RuleSetNameNotSet {
            get {
                return ResourceManager.GetString("RuleSetNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name for rule set:.
        /// </summary>
        internal static string RuleSetNewNameLableText {
            get {
                return ResourceManager.GetString("RuleSetNewNameLableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the rule set &quot;{0}&quot;. Check if rule set is defined in the rules file..
        /// </summary>
        internal static string RuleSetNotFound {
            get {
                return ResourceManager.GetString("RuleSetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Set Preview.
        /// </summary>
        internal static string RuleSetPreviewLabelText {
            get {
                return ResourceManager.GetString("RuleSetPreviewLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Rule Set.
        /// </summary>
        internal static string RuleSetRenameTitleText {
            get {
                return ResourceManager.GetString("RuleSetRenameTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rule Set.
        /// </summary>
        internal static string RuleSetTitleText {
            get {
                return ResourceManager.GetString("RuleSetTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute rule set &quot;{0}&quot; as there are validation errors..
        /// </summary>
        internal static string RuleSetValidationFailed {
            get {
                return ResourceManager.GetString("RuleSetValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule &quot;{0}&quot; validation failed. .
        /// </summary>
        internal static string RuleValidationError {
            get {
                return ResourceManager.GetString("RuleValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential.
        /// </summary>
        internal static string Sequential {
            get {
                return ResourceManager.GetString("Sequential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static member &quot;{0}&quot; cannot be accessed with an instance reference. Qualify it with a type name instead..
        /// </summary>
        internal static string StaticMember {
            get {
                return ResourceManager.GetString("StaticMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate field &quot;{0}&quot; because its target object is null..
        /// </summary>
        internal static string TargetEvaluatedNullField {
            get {
                return ResourceManager.GetString("TargetEvaluatedNullField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate indexer because its target object is null..
        /// </summary>
        internal static string TargetEvaluatedNullIndexer {
            get {
                return ResourceManager.GetString("TargetEvaluatedNullIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot invoke method &quot;{0}&quot; because its target object is null..
        /// </summary>
        internal static string TargetEvaluatedNullMethod {
            get {
                return ResourceManager.GetString("TargetEvaluatedNullMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate property &quot;{0}&quot; because its target object is null..
        /// </summary>
        internal static string TargetEvaluatedNullProperty {
            get {
                return ResourceManager.GetString("TargetEvaluatedNullProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THEN.
        /// </summary>
        internal static string Then {
            get {
                return ResourceManager.GetString("Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Evaluating {1} actions for rule &quot;{2}&quot;..
        /// </summary>
        internal static string TraceRuleActions {
            get {
                return ResourceManager.GetString("TraceRuleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rule &quot;{1}&quot; {2} side-effect: &quot;{3}&quot;.
        /// </summary>
        internal static string TraceRuleActionSideEffect {
            get {
                return ResourceManager.GetString("TraceRuleActionSideEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rule &quot;{1}&quot; {2} dependency: &quot;{3}&quot;.
        /// </summary>
        internal static string TraceRuleConditionDependency {
            get {
                return ResourceManager.GetString("TraceRuleConditionDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Evaluating condition on rule &quot;{1}&quot;..
        /// </summary>
        internal static string TraceRuleEvaluate {
            get {
                return ResourceManager.GetString("TraceRuleEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Set &quot;{0}&quot;.
        /// </summary>
        internal static string TraceRuleHeader {
            get {
                return ResourceManager.GetString("TraceRuleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Set &quot;{0}&quot;: InstanceId {1}.
        /// </summary>
        internal static string TraceRuleIdentifier {
            get {
                return ResourceManager.GetString("TraceRuleIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rule &quot;{1}&quot; condition evaluated to {2}..
        /// </summary>
        internal static string TraceRuleResult {
            get {
                return ResourceManager.GetString("TraceRuleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Executing.
        /// </summary>
        internal static string TraceRuleSetEvaluate {
            get {
                return ResourceManager.GetString("TraceRuleSetEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rule &quot;{1}&quot; {2} actions trigger rule &quot;{3}&quot;.
        /// </summary>
        internal static string TraceRuleTriggers {
            get {
                return ResourceManager.GetString("TraceRuleTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rule &quot;{1}&quot; side effects enable rule &quot;{2}&quot; reevaluation..
        /// </summary>
        internal static string TraceUpdate {
            get {
                return ResourceManager.GetString("TraceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{1}&quot; is not of type &quot;{0}&quot;..
        /// </summary>
        internal static string UnexpectedArgumentType {
            get {
                return ResourceManager.GetString("UnexpectedArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constructor on type &quot;{0}&quot; does not exist, is not accessible, or has no match with the signature specified..
        /// </summary>
        internal static string UnknownConstructor {
            get {
                return ResourceManager.GetString("UnknownConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{0}&quot; on type &quot;{1}&quot; does not exist or is not accessible..
        /// </summary>
        internal static string UnknownField {
            get {
                return ResourceManager.GetString("UnknownField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field or property &quot;{0}&quot; on type &quot;{1}&quot; does not exist or is not accessible..
        /// </summary>
        internal static string UnknownFieldOrProperty {
            get {
                return ResourceManager.GetString("UnknownFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve the generic type &quot;{0}&quot;..
        /// </summary>
        internal static string UnknownGenericType {
            get {
                return ResourceManager.GetString("UnknownGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &quot;{0}&quot; on type &quot;{1}&quot; does not exist, is not accessible, or has no match with the signature specified..
        /// </summary>
        internal static string UnknownMethod {
            get {
                return ResourceManager.GetString("UnknownMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; on type &quot;{1}&quot; does not exist or is not accessible..
        /// </summary>
        internal static string UnknownProperty {
            get {
                return ResourceManager.GetString("UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; on type &quot;{1}&quot; does not exist, does not have a property getter, or is not accessible..
        /// </summary>
        internal static string UnknownPropertyGet {
            get {
                return ResourceManager.GetString("UnknownPropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; on type &quot;{1}&quot; does not exist, does not have a property setter, or is not accessible..
        /// </summary>
        internal static string UnknownPropertySet {
            get {
                return ResourceManager.GetString("UnknownPropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type name specified (&quot;{0}&quot;) can not be resolved..
        /// </summary>
        internal static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements after the Halt action will not be executed..
        /// </summary>
        internal static string UnreachableCodeHalt {
            get {
                return ResourceManager.GetString("UnreachableCodeHalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Update action is only valid on fields or properties. The field or property to be updated should be specified as &quot;this/field&quot; or &quot;this/property&quot;..
        /// </summary>
        internal static string UpdateNotThis {
            get {
                return ResourceManager.GetString("UpdateNotThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field or property &quot;{0}&quot; specified for the Update action or RuleAttribute does not exist or is not accessible..
        /// </summary>
        internal static string UpdateUnknownFieldOrProperty {
            get {
                return ResourceManager.GetString("UpdateUnknownFieldOrProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type used for validation (&quot;{0}&quot;) is not compatible with the type of the object specified (&quot;{1}&quot;)..
        /// </summary>
        internal static string ValidationMismatch {
            get {
                return ResourceManager.GetString("ValidationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
