//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicBuilder.RuleSetToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicBuilder.RuleSetToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string anErrorHasOccurred {
            get {
                return ResourceManager.GetString("anErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleSet ToolKit.
        /// </summary>
        internal static string applicationName {
            get {
                return ResourceManager.GetString("applicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies|*.dll;*.exe.
        /// </summary>
        internal static string assembliesFilter {
            get {
                return ResourceManager.GetString("assembliesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load assembly &quot;{0}&quot;..
        /// </summary>
        internal static string cannotLoadAssemblyFormat {
            get {
                return ResourceManager.GetString("cannotLoadAssemblyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load ruleSet &quot;{0}&quot;..
        /// </summary>
        internal static string cannotLoadRuleSetFormat {
            get {
                return ResourceManager.GetString("cannotLoadRuleSetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot validate ruleSet &quot;{0}&quot;..
        /// </summary>
        internal static string cannotValidateRuleSetFormat {
            get {
                return ResourceManager.GetString("cannotValidateRuleSetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ruleSet &quot;{0}&quot;..
        /// </summary>
        internal static string invalidRuleSetFormat {
            get {
                return ResourceManager.GetString("invalidRuleSetFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Core.
        /// </summary>
        internal static string NetCore {
            get {
                return ResourceManager.GetString("NetCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Framework.
        /// </summary>
        internal static string NetFramework {
            get {
                return ResourceManager.GetString("NetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule Set.
        /// </summary>
        internal static string newRuleSetDialogTitle {
            get {
                return ResourceManager.GetString("newRuleSetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string ReevaluationAlways {
            get {
                return ResourceManager.GetString("ReevaluationAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string ReevaluationNever {
            get {
                return ResourceManager.GetString("ReevaluationNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleSet cannot be null..
        /// </summary>
        internal static string ruleSetCannotBeNull {
            get {
                return ResourceManager.GetString("ruleSetCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleSet|*.module.
        /// </summary>
        internal static string ruleSetsFiler {
            get {
                return ResourceManager.GetString("ruleSetsFiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Assembly.
        /// </summary>
        internal static string selectAssemblyDialogTitle {
            get {
                return ResourceManager.GetString("selectAssemblyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rule Set.
        /// </summary>
        internal static string selectRuleSetDialogTitle {
            get {
                return ResourceManager.GetString("selectRuleSetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be null..
        /// </summary>
        internal static string typeCannotBeNull {
            get {
                return ResourceManager.GetString("typeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP.
        /// </summary>
        internal static string UWP {
            get {
                return ResourceManager.GetString("UWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin Android.
        /// </summary>
        internal static string XamarinAndroid {
            get {
                return ResourceManager.GetString("XamarinAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin IOS.
        /// </summary>
        internal static string XamarinIOS {
            get {
                return ResourceManager.GetString("XamarinIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin UWP.
        /// </summary>
        internal static string XamarinUWP {
            get {
                return ResourceManager.GetString("XamarinUWP", resourceCulture);
            }
        }
    }
}
